name: media
services:
  bazarr:
    image: linuxserver/bazarr:1.5.2-development
    container_name: Bazarr
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/Media/Bazarr:/config
      - ${STORAGE_PATH}:/data
    ports:
      - 6767:6767
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.middlewares=crowdsec,default-headers,auth"

  radarr:
    image: linuxserver/radarr:5.18.4
    container_name: Radarr
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/Media/Radarr:/config
      - ${STORAGE_PATH}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.middlewares=crowdsec,default-headers,auth"

  sonarr:
    image: linuxserver/sonarr:4.0.13
    container_name: Sonarr
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/Media/Sonarr:/config
      - ${STORAGE_PATH}:/data #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.middlewares=crowdsec,default-headers,auth"

  prowlarr:
    image: linuxserver/prowlarr
    container_name: Prowlarr
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/Media/Prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.middlewares=crowdsec,default-headers,auth"

  qbittorrent:
    container_name: qBittorrent
    restart: unless-stopped
    image: ghcr.io/hotio/qbittorrent:release-4.6.5
    ports:
      - 8080:8080
    environment:
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_PATH}/Media/qBittorrent:/config
      - ${STORAGE_PATH}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.middlewares=crowdsec,default-headers,auth"

  jellyseerr:
    depends_on:
      - jellyfin
    image: fallenbagel/jellyseerr:2.3.0
    container_name: Jellyseerr
    environment:
      - TZ=${TIMEZONE}
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_PATH}/Media/Jellyseerr:/app/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "subdomain=add"
      - "traefik.http.routers.jellyseerr.middlewares=crowdsec,default-headers,auth"

  jellyfin:
    image: linuxserver/jellyfin:10.10.6
    container_name: Jellyfin
    environment:
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel|linuxserver/mods:jellyfin-mod2
      - TZ=${TIMEZONE}
      - JELLYFIN_PublishedServerUrl=watch.${PUBLIC_HOSTNAME}
    volumes:
      - ${CONFIG_PATH}/Media/Jellyfin:/config
      - ${STORAGE_PATH}/Media:/data
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
    devices:
      - /dev/dri/:/dev/dri/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.middlewares=crowdsec,default-headers"
      - "subdomain=watch"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: Byparr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    restart: unless-stopped

  decluttarr:
    image: ghcr.io/manimatter/decluttarr:v1.50.2
    container_name: decluttarr
    restart: always
    env_file:
      - .env.decluttarr

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:7.4
    container_name: recyclarr
    volumes:
      - ${CONFIG_PATH}/Media/Recyclarr:/config
    environment:
      - TZ=${TIMEZONE}
